name: FourDSTEM
options:
  bundleIdPrefix: com.paullobpreis
  deploymentTarget:
    macOS: "14.0"

targets:
  FourDSTEM:
    type: application
    platform: macOS
    sources:
      - path: FourDSTEM
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paullobpreis.FourDSTEM
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_OBJC_BRIDGING_HEADER: FourDSTEM/Support/FourDSTEM-Bridging-Header.h
        HEADER_SEARCH_PATHS: /opt/homebrew/opt/hdf5/include
        LIBRARY_SEARCH_PATHS: /opt/homebrew/opt/hdf5/lib
        OTHER_LDFLAGS: -lhdf5
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_STYLE: Automatic
        MACOSX_DEPLOYMENT_TARGET: "14.0"

schemes:
  FourDSTEM:
    build:
      targets:
        FourDSTEM: all
    run:
      config: Debug
