//
//  main.swift — rotation-null-probe
//
//  Measures RotationCalibration.solve's permutation null
//  (`Result.carriesRotation`) against the numbers quoted in
//  docs/open-items.md ("The rotation null is a whiteness test, not a
//  rotation test — Gate B 2026-09-15"), none of which had a checked-in
//  instrument before this file. Six experiments (A–F), each printed as one
//  row of a fixed-width table next to the recorded claim it checks.
//
//  DIAGNOSTIC: measures, asserts nothing. No experiment here calls exit(1)
//  on a disagreement with a recorded claim — disagreement is data, not a
//  failure of this harness.
//
//  All fields are generated by hand below (not imported from
//  mac4DSTEMTests/CalibrationReReferenceTests.swift), each from an
//  explicitly seeded xorshift64* RNG so every printed number is
//  reproducible from the seed alone. `maximizeDivergence` is left at its
//  default (false) throughout, per the session brief.
//

import Foundation

// MARK: - Deterministic RNG (xorshift64*, same family RotationCalibration's
// own shuffle uses, seeded explicitly per case rather than shared).

struct XorshiftRNG {
    private var state: UInt64
    init(seed: UInt64) {
        state = seed == 0 ? 0x9E3779B97F4A7C15 : seed
    }
    mutating func nextUInt64() -> UInt64 {
        state ^= state >> 12
        state ^= state << 25
        state ^= state >> 27
        return state &* 2685821657736338717
    }
    /// Uniform in [0, 1).
    mutating func nextUnit() -> Double {
        Double(nextUInt64() >> 11) * (1.0 / 9007199254740992.0) // / 2^53
    }
    /// Standard normal via Box–Muller.
    mutating func nextGaussian() -> Double {
        let u1 = Swift.max(nextUnit(), 1e-300)
        let u2 = nextUnit()
        return (-2.0 * Foundation.log(u1)).squareRoot() * cos(2.0 * Double.pi * u2)
    }
}

// MARK: - Field generators (interleaved [cx0, cy0, cx1, cy1, ...])

/// Spatially white Gaussian noise on both channels, standard deviation `sd`
/// detector pixels.
func whiteNoiseField(width: Int, height: Int, sd: Double, seed: UInt64) -> [Float] {
    var rng = XorshiftRNG(seed: seed)
    var out = [Float](repeating: 0, count: width * height * 2)
    for i in 0..<(width * height) {
        out[2 * i] = Float(rng.nextGaussian() * sd)
        out[2 * i + 1] = Float(rng.nextGaussian() * sd)
    }
    return out
}

/// 3×3 box mean of a field, each channel independently, clamped at the
/// border (averaged over whatever neighbors exist rather than wrapping or
/// zero-padding). Correlation length ≈ 2 scan px.
func boxSmoothed(_ field: [Float], width: Int, height: Int, radius: Int = 1) -> [Float] {
    if radius == 0 { return field }
    var out = [Float](repeating: 0, count: field.count)
    for y in 0..<height {
        for x in 0..<width {
            var sumX: Float = 0, sumY: Float = 0, count: Float = 0
            for dy in -radius...radius {
                let ny = y + dy
                guard ny >= 0, ny < height else { continue }
                for dx in -radius...radius {
                    let nx = x + dx
                    guard nx >= 0, nx < width else { continue }
                    let i = (ny * width + nx) * 2
                    sumX += field[i]; sumY += field[i + 1]; count += 1
                }
            }
            let o = (y * width + x) * 2
            out[o] = sumX / count
            out[o + 1] = sumY / count
        }
    }
    return out
}

/// Per-row descan drift: cx = k * row, spanning `spanPx` over the full scan
/// height, cy flat — plus independent white noise on both channels.
func rowDriftField(width: Int, height: Int, spanPx: Double, noiseSd: Double, seed: UInt64) -> [Float] {
    var rng = XorshiftRNG(seed: seed)
    var out = [Float](repeating: 0, count: width * height * 2)
    let k = height > 1 ? spanPx / Double(height - 1) : 0
    for y in 0..<height {
        let drift = k * Double(y)
        for x in 0..<width {
            let i = (y * width + x) * 2
            out[i] = Float(drift + rng.nextGaussian() * noiseSd)
            out[i + 1] = Float(rng.nextGaussian() * noiseSd)
        }
    }
    return out
}

/// A specimen edge: a step of `stepCX` in cx and `stepCY` in cy across the
/// middle column, plus independent white noise on both channels.
func specimenEdgeField(width: Int, height: Int, stepCX: Double, stepCY: Double, noiseSd: Double, seed: UInt64) -> [Float] {
    var rng = XorshiftRNG(seed: seed)
    var out = [Float](repeating: 0, count: width * height * 2)
    let mid = width / 2
    for y in 0..<height {
        for x in 0..<width {
            let i = (y * width + x) * 2
            let step = x >= mid ? 1.0 : 0.0
            out[i] = Float(step * stepCX + rng.nextGaussian() * noiseSd)
            out[i + 1] = Float(step * stepCY + rng.nextGaussian() * noiseSd)
        }
    }
    return out
}

/// The gradient of sin(x/6)*cos(y/5) (the unit test's analytic phase-object
/// potential), rotated by `angleDeg`, plus white noise sd `noiseSd` on both
/// channels.
func plantedRotationField(width: Int, height: Int, angleDeg: Double, noiseSd: Double, seed: UInt64) -> [Float] {
    var rng = XorshiftRNG(seed: seed)
    var out = [Float](repeating: 0, count: width * height * 2)
    let theta = angleDeg * .pi / 180
    let c = cos(theta), s = sin(theta)
    for y in 0..<height {
        for x in 0..<width {
            let gx = cos(Double(x) / 6) * cos(Double(y) / 5) / 6
            let gy = -sin(Double(x) / 6) * sin(Double(y) / 5) / 5
            let i = (y * width + x) * 2
            out[i] = Float(c * gx - s * gy + rng.nextGaussian() * noiseSd)
            out[i + 1] = Float(s * gx + c * gy + rng.nextGaussian() * noiseSd)
        }
    }
    return out
}

// MARK: - Small helpers

func angleDegOf(_ r: RotationCalibration.Result) -> Double {
    Double(r.rotationRad) * 180 / .pi
}

/// Error of a measured angle against a planted rotation, mod the method's
/// inherent 180° ambiguity — same construction as
/// RotationSignificanceTests.testARealRotationIsStillMeasured.
func angleErrorModHalfCircle(measuredDeg: Double, plantedDeg: Double) -> Double {
    let target = -plantedDeg
    return [measuredDeg - target, measuredDeg - target - 180, measuredDeg - target + 180]
        .map { abs($0) }
        .min()!
}

func padRight(_ s: String, _ width: Int) -> String {
    s.count >= width ? s + " " : s + String(repeating: " ", count: width - s.count)
}

func fmt(_ x: Double, _ decimals: Int = 1) -> String {
    String(format: "%.\(decimals)f", x)
}

func tableRow(_ exp: String, _ n: Int, _ measured: String, _ claim: String) -> String {
    padRight(exp, 7) + padRight("n=\(n)", 7) + padRight(measured, 96) + "| claim: " + claim
}

// MARK: - Experiments

/// A. White noise, sd 0.010, 40×40, 200 seeds → how many certify.
/// Recorded claim: under 50 of 200.
func experimentA(seedOffset: UInt64, size: Int = 40, label: String = "A", n: Int = 200) -> String {
    let width = size, height = size, sd = 0.010
    var certified = 0
    for i in 0..<n {
        let seed: UInt64 = 0xA000_0000_0000_0000 &+ seedOffset &+ UInt64(i)
        let field = whiteNoiseField(width: width, height: height, sd: sd, seed: seed)
        guard let r = RotationCalibration.solve(com: field, width: width, height: height) else { continue }
        if r.carriesRotation { certified += 1 }
    }
    let pct = Double(certified) / Double(n) * 100
    let measured = "\(certified)/\(n) certified (\(fmt(pct))%)"
    return tableRow(label, n, measured, label == "A" ? "<50/200 (<25%)" : "the demo cube's field class (shot noise, 100x100): ~1/16")
}

/// B. Box-smoothed noise, no rotation, two sizes, 60 seeds each → certified
/// count and the spread of returned angles. Recorded claim: 60–80%.
func experimentB(size: Int, label: String, radius: Int = 1, claim: String = "60-80% certified") -> String {
    let sd = 0.010, n = 60
    var certified = 0
    var angles: [Double] = []
    for i in 0..<n {
        let seed: UInt64 = 0xB000_0000_0000_0000 &+ UInt64(size) &* 1_000_000 &+ UInt64(i)
        let base = whiteNoiseField(width: size, height: size, sd: sd, seed: seed)
        let field = boxSmoothed(base, width: size, height: size, radius: radius)
        guard let r = RotationCalibration.solve(com: field, width: size, height: size) else { continue }
        if r.carriesRotation {
            certified += 1
            angles.append(angleDegOf(r))
        }
    }
    let pct = Double(certified) / Double(n) * 100
    let angleRange = angles.isEmpty ? "n/a" : "[\(fmt(angles.min()!)), \(fmt(angles.max()!))]deg"
    let measured = "\(certified)/\(n) certified (\(fmt(pct))%), certified-angle range \(angleRange)"
    return tableRow("B-\(label)", n, measured, claim)
}

/// C. Per-row descan drift, 100×100, 6 seeds → certified count, returned
/// angles, depth / max shuffled depth. Recorded claim: 6 of 6 at 6–20×.
func experimentC() -> String {
    let width = 100, height = 100, spanPx = 0.05, noiseSd = 0.010, n = 6
    var certified = 0
    var angles: [Double] = []
    var ratios: [Double] = []
    for i in 0..<n {
        let seed: UInt64 = 0xC000_0000_0000_0000 &+ UInt64(i)
        let field = rowDriftField(width: width, height: height, spanPx: spanPx, noiseSd: noiseSd, seed: seed)
        guard let r = RotationCalibration.solve(com: field, width: width, height: height) else { continue }
        if r.carriesRotation { certified += 1 }
        angles.append(angleDegOf(r))
        if let maxShuffled = r.shuffledDepths.max(), maxShuffled > 0, r.depth.isFinite {
            ratios.append(Double(r.depth) / Double(maxShuffled))
        }
    }
    let angleStr = angles.map { fmt($0) }.joined(separator: ",")
    let ratioStr = ratios.isEmpty ? "n/a" : "[\(fmt(ratios.min()!))x, \(fmt(ratios.max()!))x]"
    let measured = "\(certified)/\(n) certified; angles [\(angleStr)]deg; depth/maxShuffle \(ratioStr)"
    return tableRow("C", n, measured, "6/6 at 6-20x")
}

/// D. Specimen edge, 100×100, 6 seeds → same outputs. Recorded claim: 6 of 6.
func experimentD() -> String {
    let width = 100, height = 100, stepCX = 0.05, stepCY = 0.02, noiseSd = 0.010, n = 6
    var certified = 0
    var angles: [Double] = []
    var ratios: [Double] = []
    for i in 0..<n {
        let seed: UInt64 = 0xD000_0000_0000_0000 &+ UInt64(i)
        let field = specimenEdgeField(width: width, height: height, stepCX: stepCX, stepCY: stepCY, noiseSd: noiseSd, seed: seed)
        guard let r = RotationCalibration.solve(com: field, width: width, height: height) else { continue }
        if r.carriesRotation { certified += 1 }
        angles.append(angleDegOf(r))
        if let maxShuffled = r.shuffledDepths.max(), maxShuffled > 0, r.depth.isFinite {
            ratios.append(Double(r.depth) / Double(maxShuffled))
        }
    }
    let angleStr = angles.map { fmt($0) }.joined(separator: ",")
    let ratioStr = ratios.isEmpty ? "n/a" : "[\(fmt(ratios.min()!))x, \(fmt(ratios.max()!))x]"
    let measured = "\(certified)/\(n) certified; angles [\(angleStr)]deg; depth/maxShuffle \(ratioStr)"
    return tableRow("D", n, measured, "6/6")
}

/// E. Planted 30° rotation on the analytic phase-object gradient, sd 0.03,
/// 40×40, 60 seeds → certified count; angle error (mod 180°) distribution.
/// Recorded claim: 60 of 60, 9 over 5°, one at 61°.
/// `plantedDeg` is overridable for the sanity check (default 30).
func experimentE(plantedDeg: Double) -> String {
    let width = 40, height = 40, noiseSd = 0.03, n = 60
    var certified = 0
    var errOver5 = 0
    var maxErr = 0.0
    var angles: [Double] = []
    for i in 0..<n {
        let seed: UInt64 = 0xE000_0000_0000_0000 &+ UInt64(i)
        let field = plantedRotationField(width: width, height: height, angleDeg: plantedDeg, noiseSd: noiseSd, seed: seed)
        guard let r = RotationCalibration.solve(com: field, width: width, height: height) else { continue }
        if r.carriesRotation { certified += 1 }
        let deg = angleDegOf(r)
        angles.append(deg)
        let err = angleErrorModHalfCircle(measuredDeg: deg, plantedDeg: plantedDeg)
        if err > 5 { errOver5 += 1 }
        maxErr = Swift.max(maxErr, err)
    }
    let angleRange = angles.isEmpty ? "n/a" : "[\(fmt(angles.min()!)), \(fmt(angles.max()!))]deg"
    let measured = "\(certified)/\(n) certified; err>5deg: \(errOver5); max err \(fmt(maxErr))deg; angle range \(angleRange)"
    let claim = plantedDeg == 30
        ? "60/60; 9 over 5deg; max 61deg"
        : "n/a — sanity check, planted angle overridden to \(Int(plantedDeg))deg"
    return tableRow("E", n, measured, claim)
}

/// F. The same planted 30° rotation at noise sd 0.00, 0.01, 0.02, 0.03,
/// 0.05, 12 seeds each → refusals. Recorded claim: 0 of 60.
func experimentF() -> String {
    let width = 40, height = 40, planted = 30.0, seedsPerLevel = 12
    let sds = [0.00, 0.01, 0.02, 0.03, 0.05]
    var refused = 0
    var total = 0
    for (sdIdx, sd) in sds.enumerated() {
        for i in 0..<seedsPerLevel {
            let seed: UInt64 = 0xF000_0000_0000_0000 &+ UInt64(sdIdx) &* 1000 &+ UInt64(i)
            let field = plantedRotationField(width: width, height: height, angleDeg: planted, noiseSd: sd, seed: seed)
            guard let r = RotationCalibration.solve(com: field, width: width, height: height) else { continue }
            total += 1
            if !r.carriesRotation { refused += 1 }
        }
    }
    let measured = "\(refused)/\(total) refused (sd 0.00-0.05, 12 seeds/level)"
    return tableRow("F", total, measured, "0/60")
}

// MARK: - Main

let env = ProcessInfo.processInfo.environment
let seedOffsetA = UInt64(env["ROTATION_PROBE_SEED_OFFSET_A"] ?? "0") ?? 0
let plantedDegE = Double(env["ROTATION_PROBE_ANGLE_E"] ?? "30") ?? 30

print("rotation-null-probe — measures RotationCalibration.solve's permutation null against docs/open-items.md's Gate B 2026-09-15 claims. Diagnostic: measures, asserts nothing.")
if seedOffsetA != 0 {
    print("NOTE: experiment A seed offset overridden to \(seedOffsetA) (sanity check — not the standard run).")
}
if plantedDegE != 30 {
    print("NOTE: experiment E planted angle overridden to \(fmt(plantedDegE))deg (sanity check — not the standard run).")
}
print("")
print(padRight("EXP", 7) + padRight("N", 7) + padRight("MEASURED", 96) + "| RECORDED CLAIM")
print(String(repeating: "-", count: 150))
print(experimentA(seedOffset: seedOffsetA))
// The owner's own case class: the demo cube's descan-corrected CoM field is
// Poisson shot noise at sd ≈ 0.010 on a 100 × 100 scan (measured
// 2026-09-14, 0.01046). Its certification rate is what "Measured −67.5°"
// from that cube would recur at.
print(experimentA(seedOffset: seedOffsetA, size: 100, label: "A-100", n: 60))
print(experimentB(size: 40, label: "40"))
print(experimentB(size: 100, label: "100"))
// Gate D 2026-09-15 night: the diagnosis says the shuffle null is calibrated
// for exchangeable (white) samples, so the certification rate of a
// rotation-free field should RISE with its correlation length. Box 1 is white
// (design rate 1/16); box 5 and 7 are longer than probe overlap produces.
print(experimentB(size: 40, label: "40-box1", radius: 0, claim: "Gate D: ~1/16 (white)"))
print(experimentB(size: 40, label: "40-box5", radius: 2, claim: "Gate D: above box3 if the null is a whiteness test"))
print(experimentB(size: 40, label: "40-box7", radius: 3, claim: "Gate D: above box5"))
print(experimentC())
print(experimentD())
print(experimentE(plantedDeg: plantedDegE))
print(experimentF())
print("")
print("Legend: n = fields tested per experiment. certified = Result.carriesRotation (depth beats all 15 shuffles). "
    + "err = |measured − (−planted)| mod 180°, the method's inherent half-circle ambiguity. "
    + "depth/maxShuffle = winning-curve depth over the largest of the 15 shuffled depths (>1x is required to certify). "
    + "maximizeDivergence: false (default) throughout. Every field is generated in this file, seeded explicitly per case.")
